name: Go Application

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Run Go Application
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'  

    - name: Run Go Application
      run: go run main.go

    - id: exp
      uses: pl-strflt/job-summary-url-action@v1
    - run: echo '${{ steps.exp.outputs.job_summary_url }}'
      shell: bash
