name: Go Application

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Run Go Application
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'  

    - name: Run Go Application
      run: go run main.go
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Get Job Summary URL
      id: metadata
      uses: pl-strflt/job-summary-url-action@v1
      with:
        job: latest

    - name: Output Job Summary URL
      run: echo '${{ steps.metadata.outputs.job_summary_raw_url }}'
      shell: bash
